name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        yarn
        yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: lint
      run: |
        yarn
        yarn lint
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: coverage
      run: |
        yarn
        yarn coverage
